pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROPOSED_REPOS)
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.name = "ManageAgent"
include ':app'
